### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by janewilkin** [anko/tap-merge#1]
OMG I was googling so hard for this solution!  I'm getting my first jenkins build system up and running for the website http://bangordailynews.com and I have multiple runs of sitespeed.io & python's tappy for our own unit tests. I need to combine the tap output files from these various tools, and it looks like tap-merge will be perfect. 

YAY!!!!

**Comment by anko** [comment]
![shot](https://cloud.githubusercontent.com/assets/5231746/12381339/6daccc46-bd88-11e5-9f63-ce94df13b897.png)

I'm not quite 100% on the stability and correctness of this (hence the 0.x.x [semver](http://semver.org/)), but feel free to ping me if you get stuck or find an issue.

What search terms were you using? Maybe we could [SEO](https://en.wikipedia.org/wiki/Search_engine_optimization) the readme a bit… :smile:
